apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - image: ahmedalfeqy/dashboard:latest
        name: dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
