
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-dashboard-service
  name: my-dashboard-service
spec:
  ports:
  - name: dashboardport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: dashboard
  type: LoadBalancer
status:
  loadBalancer: {}
